src/main/webapp/boardMain.jsp, src/main/webapp/communityMain.jsp
=> boardMain.jsp communityMain.jsp added

src/main/webapp/mylist.jsp, src/main/webapp/mypageday.jsp, src/main/webapp/mypagemodi.jsp
=> kjy  mypage

src/main/webapp/editorReMain.jsp
=> editorReMain add

src/main/webapp/boardWrite.jsp
=> boardWrite.jsp add

src/main/webapp/boardWrite.jsp
=> boardWrite.jsp Modified

src/main/webapp/boardView.jsp, src/main/webapp/foodView.jsp, src/main/webapp/houseView.jsp, src/main/webapp/jobView.jsp, src/main/webapp/tripView.jsp
=> view.jsp added

src/main/webapp/boardWrite.jsp
=> boardWrite .note-editor bg_color modified

src/main/webapp/boardWrite.jsp
서머노트 툴바 좀 정리 했습니다. 몇 개 아이콘 추가되었어요.
=> boardWrit.jsp summernote toolbar add

src/main/webapp/boardMain.jsp, src/main/webapp/boardView.jsp, src/main/webapp/communityMain.jsp, src/main/webapp/editorReMain.jsp, src/main/webapp/foodMain.jsp, src/main/webapp/foodView.jsp, src/main/webapp/gallery.jsp, src/main/webapp/houseView.jsp, src/main/webapp/jobMain.jsp, src/main/webapp/jobView.jsp, src/main/webapp/mylist.jsp, src/main/webapp/mypageday.jsp, src/main/webapp/mypagemodi.jsp, src/main/webapp/signup.jsp, src/main/webapp/stayreview.jsp, src/main/webapp/tripView.jsp
1. sidebar class name Modified 
( not Modified
1-1. mylist.jsp
1-2 mypageday.jsp
1-3 signup.jsp
1-4 mypagemodi.jsp
)
2. join button Added
( not Added
2-1. mylist.jsp
2-2 mypageday.jsp
2-3 signup.jsp
2-4 mypagemodi.jsp
)
=> sidebar class name Modified All

src/main/webapp/boardMain.jsp, src/main/webapp/boardView.jsp, src/main/webapp/boardWrite.jsp, src/main/webapp/communityMain.jsp, src/main/webapp/editorReMain.jsp, src/main/webapp/foodMain.jsp, src/main/webapp/foodView.jsp, src/main/webapp/gallery.jsp, src/main/webapp/houseView.jsp, src/main/webapp/jobMain.jsp, src/main/webapp/jobView.jsp, src/main/webapp/mylist.jsp, src/main/webapp/mypageday.jsp, src/main/webapp/mypagemodi.jsp, src/main/webapp/stayreview.jsp, src/main/webapp/tripView.jsp
=> login btn color Modified

src/main/webapp/boardMain.jsp, src/main/webapp/boardView.jsp, src/main/webapp/boardWrite.jsp, src/main/webapp/communityMain.jsp, src/main/webapp/editorReMain.jsp, src/main/webapp/foodMain.jsp, src/main/webapp/foodView.jsp, src/main/webapp/gallery.jsp, src/main/webapp/houseView.jsp, src/main/webapp/jobMain.jsp, src/main/webapp/jobView.jsp, src/main/webapp/mylist.jsp, src/main/webapp/mypageday.jsp, src/main/webapp/mypagemodi.jsp, src/main/webapp/signup.jsp, src/main/webapp/stayreview.jsp, src/main/webapp/tripView.jsp
=> login modal style Added

src/main/webapp/foodView.jsp, src/main/webapp/mylist.jsp, src/main/webapp/mypageday.jsp, src/main/webapp/mypagemodi.jsp
1. foodView.jsp login Modal style Added
2. mylist.jsp joinBtn Added
3. mypageday.jsp joinBtn Added
4. mypagemodi.jsp joinBtn Added
=> joinBtn Added

src/main/webapp/boardMain.jsp, src/main/webapp/boardView.jsp, src/main/webapp/boardWrite.jsp, src/main/webapp/communityMain.jsp, src/main/webapp/editorReMain.jsp, src/main/webapp/foodMain.jsp, src/main/webapp/foodView.jsp, src/main/webapp/gallery.jsp, src/main/webapp/houseView.jsp, src/main/webapp/jobMain.jsp, src/main/webapp/jobView.jsp, src/main/webapp/mylist.jsp, src/main/webapp/mypageday.jsp, src/main/webapp/mypagemodi.jsp, src/main/webapp/stayreview.jsp, src/main/webapp/tripView.jsp
=> login library Added

src/main/webapp/boardWrite.jsp
=> bordWrite CONFLICT 

src/main/webapp/signup.jsp
=> signup.jsp modified

src/main/webapp/stayreview.jsp
=> stayreview modified

src/main/webapp/myPage.jsp
=> myPage add

src/main/webapp/boardMain.jsp, src/main/webapp/boardView.jsp, src/main/webapp/boardWrite.jsp, src/main/webapp/communityMain.jsp, src/main/webapp/editorReMain.jsp, src/main/webapp/foodMain.jsp, src/main/webapp/foodView.jsp, src/main/webapp/gallery.jsp, src/main/webapp/houseView.jsp, src/main/webapp/index.jsp, src/main/webapp/jobMain.jsp, src/main/webapp/jobView.jsp, src/main/webapp/myPage.jsp, src/main/webapp/mylist.jsp, src/main/webapp/mypageday.jsp, src/main/webapp/mypagemodi.jsp, src/main/webapp/signup.jsp, src/main/webapp/stayreview.jsp, src/main/webapp/tripView.jsp
=> scroll hidden

src/main/webapp/boardView.jsp, src/main/webapp/foodView.jsp, src/main/webapp/houseView.jsp, src/main/webapp/jobView.jsp, src/main/webapp/tripView.jsp
=> View modified

src/main/webapp/myPage.jsp
=> kjy mypage

src/main/webapp/board/boardMain.jsp, src/main/webapp/board/foodMain.jsp, src/main/webapp/board/jobMain.jsp
=> main.jsp modified

src/main/webapp/myPage.jsp
=> myPage.jsp Message Tab Add

src/main/java/controllers/FreeBoardController.java, src/main/java/dao/FreeBoardDAO.java, src/main/java/dto/FreeBoardDTO.java
자유게시판 컨트롤러, 자유게시판 DAO, 자유게시판 DTO 생성
=> FreeBoardController, FreeBoardDAO, FreeBoardDTO add

src/main/webapp/board/boardMain.jsp, src/main/webapp/board/editorReMain.jsp, src/main/webapp/board/foodMain.jsp, src/main/webapp/board/gallery.jsp, src/main/webapp/board/jobMain.jsp, src/main/webapp/board/stayreview.jsp, src/main/webapp/index.jsp, src/main/webapp/signup.jsp
=> join connected

src/main/webapp/board/gallery.jsp
=> gallery connect

src/main/java/dto/FreeBoardDTO.java
=> freeBoardDTO first add

src/main/webapp/myPage.jsp, src/main/webapp/mylist.jsp, src/main/webapp/mypageday.jsp, src/main/webapp/mypagemodi.jsp, src/main/webapp/signup.jsp
1. mylist.jsp
2. myPage.jsp
3. mypageday.jsp
4. mypagemodi.jsp
5. signup.jsp
=> weather.api Added

src/main/java/controllers/FreeBoardController.java
자유게시판 컨트로러  uri로 받아야 할 if문들 만들었습니다.
=> freeBoardController if_uri_list add

src/main/java/dto/FreeBoardDTO.java
자유게시판 DTO  멤버필드 찜 String타입으로 변겨ㅕㅇ.
=> FreeBoardDTO jjim modified

src/main/java/controllers/JjimController.java
=> JjimController create

src/main/java/controllers/FreeBoardController.java
자유게시판 컨트롤러에서 중복된 부분 있어서 삭제했습니다.
=> FreeBoardController duplication deleted

src/main/java/dto/FreeBoardDTO.java
자유게시판 DTO에서 seq 데이터타입 스트링으로 수정했습니다.
=> FreeBoardDTO seq dataType modified

src/main/java/controllers/JjimController.java
=> JjimController comment add

src/main/webapp/board/boardMain.jsp, src/main/webapp/board/boardView.jsp, src/main/webapp/board/boardWrite.jsp, src/main/webapp/board/communityMain.jsp, src/main/webapp/board/editorReMain.jsp, src/main/webapp/board/foodMain.jsp, src/main/webapp/board/foodView.jsp, src/main/webapp/board/gallery.jsp, src/main/webapp/board/houseView.jsp, src/main/webapp/board/jobMain.jsp, src/main/webapp/board/jobView.jsp, src/main/webapp/board/stayreview.jsp, src/main/webapp/board/tripView.jsp, src/main/webapp/index.jsp, src/main/webapp/mylist.jsp, src/main/webapp/mypageday.jsp, src/main/webapp/mypagemodi.jsp
=> weather api Added

src/main/webapp/myPage.jsp
=> myPage.jsp sideBar problem modified

src/main/webapp/myPage.jsp, src/main/webapp/mylist.jsp, src/main/webapp/mypageday.jsp, src/main/webapp/mypagemodi.jsp, src/main/webapp/signup.jsp
1. index.jsp
2. mylist.jsp
3. myPage.jsp
4. mypageday.jsp
5. mypagemodi.jsp
6. signup.jsp
=> login join btn Modified and Modal Modified

src/main/webapp/myPage.jsp
=> mypage 쪽지 게시글 조금 수정

src/main/webapp/myPage.jsp, src/main/webapp/mypagemodi.jsp, src/main/webapp/signup.jsp
=> myPage Modified Page UI FIXED

src/main/webapp/board/boardMain.jsp, src/main/webapp/board/boardView.jsp, src/main/webapp/board/communityMain.jsp, src/main/webapp/board/editorReMain.jsp, src/main/webapp/board/foodMain.jsp, src/main/webapp/board/foodView.jsp, src/main/webapp/board/gallery.jsp, src/main/webapp/board/houseView.jsp, src/main/webapp/board/jobMain.jsp, src/main/webapp/board/jobView.jsp, src/main/webapp/board/stayreview.jsp, src/main/webapp/board/tripView.jsp
1. board folder All .jsp file (exclude boardWrite )
=> board folder login and sidebar Modified

src/main/java/dao/FilesDAO.java, src/main/java/dto/FilesDTO.java
=> FilesDAO and FilesDTO add

src/main/java/controllers/FreeBoardController.java, src/main/java/dao/FilesDAO.java, src/main/java/dto/FilesDTO.java, src/main/webapp/board/boardWrite.jsp
게시글 작성하기 페이지에서 작성완료 버튼 클릭시 form 소스 넣어줬습니다.
그리고 filesDTO에서 parent_seq 타입을 String으로 바꾸면서 연쇄적으로 수정이 생겼습니다.
=> boardWrite.jsp form src insert and filesDAO parent_seq type modified

src/main/java/controllers/FilesController.java, src/main/webapp/board/boardWrite.jsp
작성하기 d.b저장이랑  파일 업로드 모두 잘 됩니다~.
작성할 때 올린 이미지 삭제하면 서버 폴더에서 지우는 방법 고민중...
=> boardWrite.jsp, FilesController modified

src/main/webapp/myPage.jsp
=> mypage ajax added

src/main/java/controllers/FilesController.java, src/main/webapp/board/boardWrite.jsp
서버에서 지우는 것들 우선 주석 처리했습니다.... 마지막으로 빼야 할 것 같아요
=> 서머노트 이미지 지울 때 서버에서  지우기

src/main/webapp/board/boardMain.jsp, src/main/webapp/board/boardView.jsp, src/main/webapp/board/boardWrite.jsp, src/main/webapp/board/communityMain.jsp, src/main/webapp/board/editorReMain.jsp, src/main/webapp/board/foodMain.jsp, src/main/webapp/board/foodView.jsp, src/main/webapp/board/gallery.jsp, src/main/webapp/board/houseView.jsp, src/main/webapp/board/jobMain.jsp, src/main/webapp/board/jobView.jsp, src/main/webapp/board/stayreview.jsp, src/main/webapp/board/tripView.jsp, src/main/webapp/index.jsp, src/main/webapp/myPage.jsp, src/main/webapp/signup.jsp
=> mypage connect

src/main/webapp/board/boardView.jsp
=> boardView.jsp modified

src/main/java/controllers/BoardController.java, src/main/java/dao/BoardDAO.java, src/main/webapp/board/boardWrite.jsp
게시판 선택해서 작성완료 시 insert되게 했습니다.
=> board insert merge

src/main/java/controllers/BoardController.java, src/main/java/dao/BoardDAO.java, src/main/webapp/board/boardWrite.jsp
=> bordWrite editor option add

src/main/webapp/board/boardView.jsp, src/main/webapp/board/foodView.jsp, src/main/webapp/board/houseView.jsp, src/main/webapp/board/jobView.jsp, src/main/webapp/board/tripView.jsp
=> view.jsp modified

src/main/java/controllers/BoardController.java
=> BoardController modified

src/main/java/controllers/BoardController.java, src/main/java/dao/BoardDAO.java, src/main/java/dto/BoardDTO.java
게시판 DTO에 jjim_count 추가하고  그에 따른 연쇄 에러 수정
=> jjim_count add

src/main/webapp/index.jsp
=> index.jsp background-image modified

src/main/java/controllers/BoardController.java
=> BoardController writeProcessing modified

src/main/webapp/myPage.jsp
=> Calendar added

src/main/webapp/board/editorReMain.jsp
=> editor modified

src/main/webapp/board/boardMain.jsp, src/main/webapp/board/foodMain.jsp, src/main/webapp/board/gallery.jsp, src/main/webapp/board/jobMain.jsp, src/main/webapp/board/stayreview.jsp
=> kjy    top 버튼 수정했어요

src/main/webapp/board/boardView.jsp, src/main/webapp/board/foodView.jsp, src/main/webapp/board/houseView.jsp, src/main/webapp/board/jobView.jsp, src/main/webapp/board/tripView.jsp
=> fileList.jsp modified

src/main/java/controllers/BoardController.java, src/main/java/dao/BoardDAO.java, src/main/java/dao/JjimDAO.java, src/main/java/dto/JjimDTO.java
BoradController작업, JjimADO, JjimDTO 생성
=> 찜, 좋아요 선택 시 back 작업

src/main/java/controllers/BoardController.java, src/main/java/dao/BoardDAO.java, src/main/webapp/board/boardMain.jsp, src/main/webapp/index.jsp
1. navibar Added
2. Temporarily change community links for testing
=> navibar Added

src/main/webapp/board/editorReMain.jsp
=> remain topbotton추가

src/main/webapp/board/boardMain.jsp
1. boardMain.jsp Datefmt Modified
=> Datefmt Modified

src/main/webapp/board/boardMain.jsp, src/main/webapp/board/boardView.jsp, src/main/webapp/board/boardWrite.jsp, src/main/webapp/board/communityMain.jsp, src/main/webapp/board/foodMain.jsp, src/main/webapp/board/gallery.jsp, src/main/webapp/board/houseView.jsp, src/main/webapp/board/jobMain.jsp, src/main/webapp/board/stayreview.jsp, src/main/webapp/myPage.jsp, src/main/webapp/mylist.jsp
1. boardMain.jsp - hover Modified, navibar Added
2. boardView.jsp - hover Modified
3. boardWrite.jsp - hover Modified
4. communityMain.jsp - hover Modified
5. foodMain.jsp - hover Modified, navibar Added
6. gallery.jsp - hover Modified, navibar Added
7. houseView.jsp - hover Modified
8. jobMain.jsp - hover Modified, navibar Added
9. stayreview.jsp - hover Modified, navibar Added
10. mylist.jsp - hover Modified
11. myPage.jsp - hover Modified
=> hover Modified and navibar Added

src/main/webapp/index.jsp, src/main/webapp/signup.jsp
1. input css Modified
2. password eyes Modified
3. index.jsp background img Modified
=> signup.jsp input and eyes Modified

src/main/webapp/board/boardMain.jsp, src/main/webapp/board/boardView.jsp, src/main/webapp/board/boardWrite.jsp, src/main/webapp/board/communityMain.jsp, src/main/webapp/board/editorReMain.jsp, src/main/webapp/board/foodMain.jsp, src/main/webapp/board/foodView.jsp, src/main/webapp/board/gallery.jsp, src/main/webapp/board/houseView.jsp, src/main/webapp/board/jobMain.jsp, src/main/webapp/board/jobView.jsp, src/main/webapp/board/stayreview.jsp, src/main/webapp/board/tripView.jsp, src/main/webapp/myPage.jsp, src/main/webapp/mylist.jsp
1. boardMain.jsp - joinbtn Added
2. boardView.jsp - joinbtn Added, modal Added, scroll hidden
3. boardWrite.jsp - summurnote div Modified, joinbtn Added, modal Added
4. communityMain.jsp - joinbtn Added
5. editorReMain.jsp - joinbtn Added, modal Added
6. gallary.jsp - loginbtn Added
7. foodMain.jsp - joinbtn Added, modal Added
8. foodView.jsp - joinbtn Added, modal Added, weather api Added, scroll hidden
9. houseview.jsp - joinbtn Added, modal Added, weather api Added, toggle color Modified, scroll hidden
10. jobView.jsp - joinbtn Added, modal Added, weather api Added, toggle color Modified, scroll hidden
11. jobMain.jsp - loginbtn Added
12. tripView.jsp - joinbtn Added, modal Added, weather api Added, toggle color Modified, scroll hidden
=> modal login Btn Added

src/main/webapp/board/boardMain.jsp, src/main/webapp/board/boardView.jsp, src/main/webapp/board/boardWrite.jsp, src/main/webapp/board/communityMain.jsp, src/main/webapp/board/editorReMain.jsp, src/main/webapp/board/foodMain.jsp, src/main/webapp/board/foodView.jsp, src/main/webapp/board/gallery.jsp, src/main/webapp/board/houseView.jsp, src/main/webapp/board/jobMain.jsp, src/main/webapp/board/jobView.jsp, src/main/webapp/board/stayreview.jsp, src/main/webapp/board/tripView.jsp, src/main/webapp/index.jsp, src/main/webapp/myPage.jsp, src/main/webapp/mylist.jsp, src/main/webapp/signup.jsp
=> navibar Modified loginbtn Modified

src/main/java/controllers/BoardController.java, src/main/java/controllers/FilesController.java, src/main/java/dao/BoardDAO.java, src/main/java/dao/FilesDAO.java, src/main/webapp/board/boardMain.jsp, src/main/webapp/board/boardView.jsp, src/main/webapp/board/boardWrite.jsp
자유게시판 메인 boardMain.jsp에서  게시글 목록_제목에 링크 걸어줌 -> 컨트롤러 거쳐서 boardView,jsp로 넘어가게 / 링그 글씨?(파란색) 추후 CSS 수정 필요
//조회수 기능 완성
//작성하기(boardWrite.jsp)에서 작성완료 버튼 클릭 시 로그인 안 했으면 경고창 나오게 기능 추가.
//파일 다운로드 기능 구현
(파일 리스트 목록에  업로드한 파일 + contents 영역에 올린 이미지까지 나옴  
/이런 게시글들도 본 것 같은데 괜찮은지 회의? 필요할 듯.     contetns 영역에 올린 이미지는 파일 리스트 목록에서 빼고 싶으면 가능은 하나, 좀 대대적 작업 필요.(원인은 boardWrite.jsp에서 contents영역이 multipart form 영역 안에 있어서  같은 컨트롤러로 넘어가기 때문. )
=> 자유게시판 목록 boardView 연결 + 조회수 기능 구현 + 파일 다운로드 기능 구현

src/main/webapp/board/boardView.jsp
=> .view changed design

src/main/java/controllers/FilesController.java
=> FilesController realPath modified

src/main/webapp/signup.jsp
=> accodion Modified

src/main/webapp/board/boardView.jsp, src/main/webapp/board/boardWrite.jsp, src/main/webapp/board/communityMain.jsp, src/main/webapp/board/foodView.jsp, src/main/webapp/board/houseView.jsp, src/main/webapp/board/jobView.jsp, src/main/webapp/board/tripView.jsp, src/main/webapp/index.jsp, src/main/webapp/signup.jsp
=> top button 추가

src/main/webapp/board/foodMain.jsp, src/main/webapp/myPage.jsp
=> foodmain nvbar

src/main/webapp/board/boardMain.jsp, src/main/webapp/board/communityMain.jsp, src/main/webapp/board/editorReMain.jsp, src/main/webapp/board/foodMain.jsp, src/main/webapp/board/gallery.jsp, src/main/webapp/board/houseMain.jsp, src/main/webapp/board/jobMain.jsp
=> housemain tag

src/main/webapp/board/communityMain.jsp
=> communityMain.jsp nav nav2 modified

src/main/webapp/board/jobMain.jsp, src/main/webapp/signup.jsp
1. signup.jsp - signinBtn disabled Modified
=> signinBtn disabled Modified

src/main/webapp/board/boardView.jsp
=> reply modified

src/main/webapp/board/messageView.jsp, src/main/webapp/message.html
=> messageView.jsp

src/main/webapp/board/boardMain.jsp
1. boardMain.jsp hotlist Modified
=> hotlist Modified

src/main/webapp/board/boardView.jsp
=> boardView.jsp weather Added

src/main/webapp/board/boardMain.jsp, src/main/webapp/board/foodMain.jsp, src/main/webapp/board/houseMain.jsp, src/main/webapp/board/jobMain.jsp
1. boardMain.jsp
2. foodMain.jsp
3. houseMain.jsp
4. jobMain.jsp
5.
=> login jstl Modified

src/main/webapp/board/boardView.jsp
=> like modified

src/main/webapp/board/boardView.jsp
=> error modified

src/main/java/controllers/BoardController.java, src/main/java/dao/BoardDAO.java, src/main/webapp/board/foodMain.jsp, src/main/webapp/board/gallery.jsp, src/main/webapp/board/houseMain.jsp, src/main/webapp/board/jobMain.jsp
1. BoardController.java
2. foodMain.jsp
3. gallery.jsp
4. houseMain.jsp
5. jobMain.jsp
=> navipage Added and list Added

src/main/webapp/board/boardMain.jsp, src/main/webapp/board/foodMain.jsp, src/main/webapp/board/gallery.jsp, src/main/webapp/board/houseMain.jsp, src/main/webapp/board/jobMain.jsp
1. boardMain.jsp
2. foodMain.jsp
3. houseMain.jsp
=> writeBtn Added

src/main/webapp/board/boardWrite.jsp
작성하기 콤보박스에서 후기, 애디터 추천 선택 시 프로필 선택하도록 기능 추가
=> boardWrite_selectCombobox modified

src/main/java/dao/FilesDAO.java
=> FilesDAO_selectSysName add

src/main/webapp/board/boardView.jsp
=> 대댓글 작성하기까지 일단 구현

src/main/webapp/board/gallery.jsp
=> gleery_profile modified

src/main/java/dao/BoardDAO.java, src/main/webapp/board/gallery.jsp
1. BoardDAO.java
2. gallery.jsp
=> navi Argorithm Modified

src/main/webapp/board/boardModi.jsp, src/main/webapp/board/boardWrite.jsp, src/main/webapp/board/messageView.jsp, src/main/webapp/myPage.jsp
1. boardModi.jsp
2. boardWrite.jsp
3. myPage.jsp
=> alert for loginID null Added

src/main/java/controllers/MyPageController.java, src/main/java/dao/MessageDAO.java, src/main/java/dto/MessageDTO.java, src/main/webapp/myPage.jsp
MessageDTO,DAO and MyPageController added
=> MessageDTO,DAO and MyPageController added

src/main/webapp/board/boardWrite.jsp, src/main/webapp/myPage.jsp
1. boardWrite.jsp
2. myPage.jsp
=> loginId null for alert Modified

src/main/java/controllers/ReplyController.java, src/main/webapp/board/boardView.jsp
리스트까지 나오고 댓글 등록 되지만 아직 등록하면 리스트에 바로 반영 안됨
=> rereply list

src/main/java/controllers/ReplyController.java, src/main/webapp/board/boardView.jsp
=> rereply delete

src/main/java/controllers/BoardController.java, src/main/webapp/board/editorReMain.jsp
자유게시판 컨트롤러에서 디테일뷰 쪽에 조회수 증가시키는 부분 수정
=> boardController_detailVeiw_viewCount modified

src/main/java/controllers/MyPageController.java, src/main/java/dao/MessageDAO.java, src/main/java/dto/MessageDTO.java, src/main/webapp/board/messageView.jsp, src/main/webapp/myPage.jsp
=> MessageDetailView added

src/main/webapp/board/editorReMain.jsp
=> editorReMain like,jjim complete

src/main/webapp/board/boardView.jsp
=> boardview 정렬

src/main/java/controllers/MemberController.java, src/main/webapp/myPage.jsp
=> myPage user Modified Fixed

src/main/java/controllers/BoardController.java, src/main/java/dao/BoardDAO.java, src/main/webapp/board/boardMain.jsp
=> boardMain search

src/main/webapp/myPage.jsp
=> myPage userModified Fixed

src/main/java/controllers/MemberController.java, src/main/java/dao/MemberDAO.java, src/main/webapp/board/gallery.jsp, src/main/webapp/myPage.jsp
1. myPage.jsp userModified savepoint
=> myPage user Modified FIXING (savepoint)

src/main/java/controllers/MemberController.java, src/main/java/controllers/MyPageController.java, src/main/java/dao/MemberDAO.java, src/main/java/dao/MessageDAO.java, src/main/webapp/board/messageView.jsp
1. messageView.jsp
2. MyPageController.java
3. MessageDAO.java
4. MessageDTO.java
=> Message Send, Delete, DetailVeiw added fixed

src/main/java/controllers/BoardController.java, src/main/webapp/board/boardMain.jsp
=>  boardMain editorRe complete

src/main/java/controllers/BoardController.java, src/main/webapp/board/jobMain.jsp
=> boardMain editor_link and viewCount

src/main/java/controllers/BoardController.java, src/main/webapp/board/foodMain.jsp
=> foodMain editorRe complete

src/main/java/controllers/BoardController.java
자유게시판 메인에서 검색 시 애디터추천 나오게 코드 추가
=>  BaordController_search modified

src/main/java/controllers/BoardController.java, src/main/java/dao/BoardDAO.java, src/main/webapp/board/foodMain.jsp, src/main/webapp/board/gallery.jsp
=> gllery_search complete

src/main/java/controllers/BoardController.java, src/main/java/dao/BoardDAO.java, src/main/webapp/board/gallery.jsp
=> search pagingNavi modified

src/main/java/controllers/BoardController.java, src/main/webapp/board/jobMain.jsp
=> jobMain search

src/main/java/controllers/BoardController.java, src/main/webapp/board/boardMain.jsp, src/main/webapp/board/boardModi.jsp, src/main/webapp/board/foodMain.jsp, src/main/webapp/board/gallery.jsp, src/main/webapp/board/houseMain.jsp, src/main/webapp/board/jobMain.jsp
기존 조회수 이전 페이지면 if 증가는 여러 애로사항이 생김. 검색 시, 페이징 넘버 클릭 시 주소가 계속 달라짐//
해당 제목 클릭 시 파라미터를 던져서 
컨트롤러에서 받아 if문으로 해결
=> view_count all modified

src/main/webapp/board/editorReMain.jsp
=> editorReMain link

src/main/java/controllers/ReplyController.java, src/main/java/dao/ReplyDAO.java, src/main/webapp/board/boardView.jsp
=> reply select method modified

src/main/webapp/myPage.jsp
=> myPage Modified

src/main/java/controllers/BoardController.java, src/main/webapp/board/boardMain.jsp, src/main/webapp/board/foodMain.jsp, src/main/webapp/board/houseMain.jsp, src/main/webapp/board/jobMain.jsp
=>  boardWrite btn link modified

src/main/webapp/board/gallery.jsp
=> galleryMain boardWrite add

src/main/java/controllers/BoardController.java, src/main/webapp/board/boardWrite.jsp
작성하기 버튼 눌러서 작성하기 페이지로 갈 때
콤보박스 해당 게시글로 자동 set 되게.
=> boardWrite comboBox auto set

src/main/java/controllers/BoardController.java
=> boardWrite complete btn link modified

src/main/java/controllers/BoardController.java, src/main/java/dao/BoardDAO.java, src/main/java/dto/BoardDTO.java
=> BoardDTO lind add

src/main/java/dao/BoardDAO.java, src/main/webapp/board/boardMain.jsp, src/main/webapp/board/foodMain.jsp, src/main/webapp/board/houseMain.jsp, src/main/webapp/board/jobMain.jsp
=> board line number add

src/main/java/dao/BoardDAO.java
=> BoardDAO selectByPage modified

src/main/java/dao/BoardDAO.java
=> BoardDAO insert modified

src/main/java/dao/MessageDAO.java, src/main/webapp/board/messageView.jsp, src/main/webapp/myPage.jsp
sendMsgBtn added fixed, history.back & modalsend added, MsgDAO sql fixed
=> MessageBtn added

src/main/webapp/board/boardWrite.jsp
글 작성  해당 게시글 자동 seleced 되는 부분 수정
=> boardWrite board selected modified

src/main/java/controllers/MyPageController.java, src/main/webapp/myPage.jsp
=> Messagetab added

src/main/java/controllers/BoardController.java
=> boardwrite modify

src/main/java/controllers/BoardController.java, src/main/java/dao/BoardDAO.java, src/main/webapp/board/communityMain.jsp
=> coummityMain CONFLICT modified

src/main/java/controllers/MyPageController.java, src/main/java/dao/MessageDAO.java, src/main/java/dto/MessageDTO.java
=> Messagetab conflict modified

src/main/webapp/board/boardMain.jsp, src/main/webapp/board/boardModi.jsp, src/main/webapp/board/boardView.jsp, src/main/webapp/board/boardWrite.jsp, src/main/webapp/board/communityMain.jsp, src/main/webapp/board/editorReMain.jsp, src/main/webapp/board/foodMain.jsp, src/main/webapp/board/gallery.jsp, src/main/webapp/board/houseMain.jsp, src/main/webapp/board/jobMain.jsp, src/main/webapp/board/messageView.jsp, src/main/webapp/index.jsp, src/main/webapp/myPage.jsp, src/main/webapp/signup.jsp
=> sidebar Modified

src/main/java/controllers/MyPageController.java, src/main/webapp/board/boardMain.jsp, src/main/webapp/board/boardModi.jsp, src/main/webapp/board/boardView.jsp, src/main/webapp/board/boardWrite.jsp, src/main/webapp/board/communityMain.jsp, src/main/webapp/board/editorReMain.jsp, src/main/webapp/board/foodMain.jsp, src/main/webapp/board/gallery.jsp, src/main/webapp/board/houseMain.jsp, src/main/webapp/board/jobMain.jsp, src/main/webapp/board/messageView.jsp, src/main/webapp/index.jsp, src/main/webapp/myPage.jsp, src/main/webapp/signup.jsp
=> myPage Controller Connect

src/main/webapp/board/boardMain.jsp, src/main/webapp/board/foodMain.jsp, src/main/webapp/board/gallery.jsp, src/main/webapp/board/houseMain.jsp, src/main/webapp/board/jobMain.jsp
1. boardMain.jsp
2. foodMain.jsp
3. gallery.jsp
4. houseMain.jsp
5. jobMain.jsp
=> write block if session null

src/main/webapp/board/boardMain.jsp, src/main/webapp/board/boardModi.jsp, src/main/webapp/board/boardView.jsp, src/main/webapp/board/boardWrite.jsp, src/main/webapp/board/communityMain.jsp, src/main/webapp/board/editorReMain.jsp, src/main/webapp/board/foodMain.jsp, src/main/webapp/board/gallery.jsp, src/main/webapp/board/houseMain.jsp, src/main/webapp/board/jobMain.jsp, src/main/webapp/myPage.jsp
=> top bar Modified

src/main/webapp/board/boardMain.jsp, src/main/webapp/board/communityMain.jsp, src/main/webapp/board/gallery.jsp, src/main/webapp/board/houseMain.jsp, src/main/webapp/board/jobMain.jsp
1. boardMain.jsp
2. gallery.jsp
3. houseMain.jsp
4. jobMain.jsp
=> font and layout Modified

src/main/webapp/board/boardMain.jsp, src/main/webapp/board/boardModi.jsp, src/main/webapp/board/boardView.jsp, src/main/webapp/board/boardWrite.jsp, src/main/webapp/board/communityMain.jsp, src/main/webapp/board/editorReMain.jsp, src/main/webapp/board/foodMain.jsp, src/main/webapp/board/gallery.jsp, src/main/webapp/board/houseMain.jsp, src/main/webapp/board/jobMain.jsp, src/main/webapp/board/messageView.jsp
=> display property Modified

src/main/java/controllers/BoardController.java, src/main/java/dao/MemberDAO.java, src/main/webapp/board/boardWrite.jsp
=> MemberDAO adminImformation add

src/main/java/controllers/BoardController.java, src/main/webapp/board/boardWrite.jsp
관리자 계정으로 작성하기 시 type 'n'으로 insert되게.
=>  admin boardWrite_notice insert modified

src/main/java/dao/BoardDAO.java, src/main/webapp/board/boardWrite.jsp
=> boardWrite insert modified

src/main/java/controllers/BoardController.java, src/main/java/dao/BoardDAO.java, src/main/webapp/board/boardMain.jsp
=> boardMain notice complete

src/main/webapp/board/boardWrite.jsp
=> boardWrite modified

src/main/java/controllers/BoardController.java, src/main/webapp/board/foodMain.jsp
=> foodMain notice complete

src/main/java/controllers/BoardController.java, src/main/webapp/board/houseMain.jsp
=> houseMain notice

src/main/java/controllers/MyPageController.java
=> Message tab added

src/main/webapp/board/boardView.jsp
게시글 detailView에서 쪽지 보낼 수 있는 기능 완.
=>  boardView message complete

src/main/java/controllers/AdminController.java, src/main/webapp/adminPage.jsp
=> adminPage boardList

src/main/java/controllers/AdminController.java, src/main/java/dao/BoardDAO.java, src/main/webapp/adminPage.jsp
관리자 게시글 페이징 네비 
관리자 전용 필요해서 boardDAO에 하나 만듦
=>  adminPage_navi modified

src/main/java/controllers/AdminController.java, src/main/java/dao/BoardDAO.java, src/main/webapp/adminPage.jsp
관리자 페이지 게시글 탭 완성.
단, 검색 취소 하는 기능 필요한 듯. 작업 중...
=> adminPage search complete

src/main/java/controllers/AdminController.java, src/main/webapp/adminPage.jsp
=> adminPage search_cancel complete

src/main/java/controllers/BoardController.java, src/main/java/controllers/MyPageController.java, src/main/java/dao/MessageDAO.java, src/main/java/dto/BoardDTO.java, src/main/webapp/myPage.jsp
=> MyPage Booadlist added fixed

src/main/webapp/board/boardView.jsp
우선 관리자인 경우는 모든 게시글 수정 삭제 버튼  보이게 함
=> boardView modified

src/main/java/controllers/MyPageController.java, src/main/webapp/board/messageView.jsp, src/main/webapp/myPage.jsp
=> Mypage padding arrangement

src/main/webapp/board/boardWrite.jsp
=> boardWrite

src/main/webapp/board/boardModi.jsp
수정 시 첫 번째 파일 삭제하면 프로필 선택하게 하는 기능 완성
=> boardModi selectBox modified

src/main/webapp/board/boardWrite.jsp
작성하기 
타이틀  space만 입력한 경우 작성완료 안되게  막음/
글자길이 50byte 넘기면 작성완료 안되게 막음
=>  boardWrite title length

src/main/webapp/board/boardModi.jsp, src/main/webapp/board/boardWrite.jsp
=> title length and space

src/main/webapp/board/boardModi.jsp, src/main/webapp/board/boardWrite.jsp, src/main/webapp/board/houseMain.jsp
=> editor renamed

src/main/webapp/board/boardMain.jsp
=> boardMain carousel

src/main/webapp/board/foodMain.jsp
=>  foodMain carousel modified

src/main/webapp/board/houseMain.jsp
=> houseMain carousel modified

src/main/java/dao/BoardDAO.java
=> boardDAO modified

src/main/java/controllers/AdminController.java, src/main/java/dao/MemberDAO.java, src/main/webapp/adminPage.jsp
=> 관리자페이지 검색기능 추가

src/main/webapp/board/boardWrite.jsp
작성하기 파일 업로드 10mb 넘으면 경고창 뜸 //
서머노트도 이미지 업로드 시 10mb 넘으면 경고창 뜸
=> fileMaxSize

src/main/webapp/board/boardModi.jsp
수정하기 파일 업로드 용량 10mb 넘으면 경고창 //
서머노트 이미지 업로드 용량 10mb 넘으면 경고창
=> boardModi fileSize limit

src/main/webapp/adminPage.jsp
=> adminPage tab3 delete

src/main/webapp/myPage.jsp
=> 제목 text-align center적용

src/main/webapp/signup.jsp
=> signup 로그인, 회원가입 가능

src/main/webapp/adminPage.jsp
adminPage search cancel btn added
=> adminPage search cancel btn added

src/main/java/controllers/AdminController.java, src/main/java/dao/MemberDAO.java, src/main/webapp/adminPage.jsp
관리자 계정 탭에서 가입일로 검색할 수 있는 기능 추가
=> admin tab2 date_search

src/main/webapp/adminPage.jsp
adminpage search cancel added if문 제거
=> adminpage search cancel added if문 제거

src/main/webapp/board/boardMain.jsp, src/main/webapp/board/foodMain.jsp, src/main/webapp/board/jobMain.jsp
=> card modified

src/main/webapp/adminPage.jsp, src/main/webapp/myPage.jsp
adminPage Member infiniedScroll
=> adminPage Member infiniedScroll

src/main/java/controllers/AdminController.java, src/main/java/dao/MemberDAO.java, src/main/webapp/adminPage.jsp
=> adminPage modified

src/main/java/dao/BoardDAO.java, src/main/webapp/adminPage.jsp
검색 시 총 레코드 개수를 검색 기준으로 잡아야 하는데 기존 검색 전 게시글들 수로 잡고 있어서 페이징 네비 수가 검색 전과 같은 오류 발생해서 해결
=> BoardDAO search_paging modified

src/main/webapp/board/boardModi.jsp, src/main/webapp/board/boardWrite.jsp
=> fileSize limit modified

src/main/webapp/board/boardModi.jsp, src/main/webapp/board/boardWrite.jsp
=> ctrl v prevent

src/main/webapp/board/boardWrite.jsp
=>  boardWrite link modified

src/main/webapp/adminPage.jsp
관리자 페이지 게시글 옵션에 에디터 추천 없어서 집어넣음
=> adminPage boardCobmboBox editor option add

src/main/webapp/board/boardWrite.jsp
=> 커뮤니티메인보드로연결
